const countryCodes = {
  "93": { name: "Afghanistan", warning: "red" },
  "355": { name: "Albania", warning: "yellow" },
  "213": { name: "Algeria" },
  "376": { name: "Andorra" },
  "244": { name: "Angola" },
  "1": { name: "United States" },
  "54": { name: "Argentina" },
  "374": { name: "Armenia" },
  "61": { name: "Australia" },
  "43": { name: "Austria" },
  "994": { name: "Azerbaijan" },
  "973": { name: "Bahrain" },
  "880": { name: "Bangladesh" },
  "375": { name: "Belarus", warning: "red" },
  "32": { name: "Belgium" },
  "591": { name: "Bolivia" },
  "387": { name: "Bosnia and Herzegovina", warning: "yellow" },
  "267": { name: "Botswana" },
  "55": { name: "Brazil" },
  "359": { name: "Bulgaria", warning: "yellow" },
  "226": { name: "Burkina Faso" },
  "95": { name: "Burma/Myanmar", warning: "red" },
  "236": { name: "Central African Republic", warning: "red" },
  "86": { name: "China", warning: "yellow" },
  "57": { name: "Colombia" },
  "242": { name: "Republic of the Congo", warning: "red" },
  "243": { name: "Democratic Republic of the Congo", warning: "red" },
  "506": { name: "Costa Rica" },
  "385": { name: "Croatia", warning: "yellow" },
  "53": { name: "Cuba", warning: "red" },
  "357": { name: "Cyprus" },
  "420": { name: "Czech Republic" },
  "45": { name: "Denmark" },
  "253": { name: "Djibouti" },
  "1-809": { name: "Dominican Republic" },
  "593": { name: "Ecuador" },
  "20": { name: "Egypt" },
  "503": { name: "El Salvador" },
  "291": { name: "Eritrea", warning: "yellow" },
  "372": { name: "Estonia" },
  "251": { name: "Ethiopia", warning: "yellow" },
  "358": { name: "Finland" },
  "33": { name: "France" },
  "49": { name: "Germany" },
  "233": { name: "Ghana" },
  "30": { name: "Greece" },
  "502": { name: "Guatemala" },
  "224": { name: "Guinea" },
  "509": { name: "Haiti" },
  "504": { name: "Honduras" },
  "852": { name: "Hong Kong", warning: "yellow" },
  "36": { name: "Hungary" },
  "91": { name: "India" },
  "62": { name: "Indonesia" },
  "98": { name: "Iran", warning: "red" },
  "964": { name: "Iraq", warning: "red" },
  "353": { name: "Ireland" },
  "972": { name: "Israel" },
  "39": { name: "Italy" },
  "225": { name: "Ivory Coast", warning: "yellow" },
  "1-876": { name: "Jamaica" },
  "81": { name: "Japan" },
  "962": { name: "Jordan" },
  "7": { name: "Russia", warning: "red" },
  "254": { name: "Kenya" },
  "965": { name: "Kuwait" },
  "371": { name: "Latvia" },
  "961": { name: "Lebanon", warning: "red" },
  "231": { name: "Liberia", warning: "yellow" },
  "218": { name: "Libya", warning: "red" },
  "370": { name: "Lithuania" },
  "352": { name: "Luxembourg" },
  "265": { name: "Malawi" },
  "60": { name: "Malaysia" },
  "223": { name: "Mali", warning: "red" },
  "356": { name: "Malta" },
  "230": { name: "Mauritius" },
  "52": { name: "Mexico" },
  "373": { name: "Moldova" },
  "382": { name: "Montenegro", warning: "yellow" },
  "212": { name: "Morocco" },
  "258": { name: "Mozambique" },
  "977": { name: "Nepal" },
  "505": { name: "Nicaragua", warning: "red" },
  "31": { name: "Netherlands" },
  "64": { name: "New Zealand" },
  "234": { name: "Nigeria" },
  "47": { name: "Norway" },
  "92": { name: "Pakistan" },
  "507": { name: "Panama" },
  "595": { name: "Paraguay" },
  "51": { name: "Peru" },
  "63": { name: "Philippines" },
  "48": { name: "Poland" },
  "351": { name: "Portugal" },
  "974": { name: "Qatar" },
  "40": { name: "Romania", warning: "yellow" },
  "381": { name: "Serbia", warning: "yellow" },
  "386": { name: "Slovenia", warning: "yellow" },
  "27": { name: "South Africa" },
  "211": { name: "South Sudan", warning: "red" },
  "82": { name: "South Korea" },
  "34": { name: "Spain" },
  "94": { name: "Sri Lanka" },
  "249": { name: "Sudan", warning: "red" },
  "963": { name: "Syria", warning: "red" },
  "90": { name: "Turkey", warning: "yellow" },
  "256": { name: "Uganda" },
  "380": { name: "Ukraine" },
  "971": { name: "United Arab Emirates" },
  "44": { name: "United Kingdom" },
  "598": { name: "Uruguay" },
  "998": { name: "Uzbekistan" },
  "58": { name: "Venezuela", warning: "red" },
  "84": { name: "Vietnam" },
  "967": { name: "Yemen", warning: "red" },
  "263": { name: "Zimbabwe", warning: "red" }
};
